-
 
 name: This playbook will install docker based on OS distribution
 hosts: servers
 become: yes
 tasks:
   - name: install Docker
     yum:
       name: docker
       state: latest
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
   - name: install  aws cli
     apt: 
      name: awscli
      state: latest
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
